# Generated by Django 5.1.3 on 2024-12-01 18:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('daraja', models.CharField(choices=[('Junior', 'Junior'), ('Senior', 'Senior'), ('Staff', 'Staff')], max_length=50)),
                ('Ustoz', models.CharField(choices=[('Otabek', 'Otabek'), ('Abbos', 'Abbos')], max_length=50)),
                ('narx', models.CharField(max_length=50)),
                ('chegirma_narx', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('yosh', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(60)])),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profillar',
            },
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('baho', models.IntegerField()),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Tanlangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profil')),
            ],
        ),
        migrations.CreateModel(
            name='Xarid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('holat', models.CharField(max_length=50)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kurs')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profil')),
            ],
        ),
    ]
